### ISSUE TITLE
Adding a new IP to a present interface destroys the networking of the normal containers.

### ISSUE THREAD

**Issue by AlessandroEmm** [docker-infra/haproxy-docker#5]
Hey There

I really like your idea and I was eagerly trying it out.

Now my Problem is whenever I add a new IP to a present interface it destroys the networking of the normal containers that listen on the original ip (primary of the interface).
I can't access them anymore while haproxy listens just fine on the newly added IP.

Have you had similar experiences?

Regards
Alessandro

**Comment by discordianfish** [comment]
I'm not sure I understand the problem: Is this a general thing? As soon as you add a new IP to your interface, your container's network isn't working anymore? If this is the case, can you open a issue for docker itself?

**Comment by AlessandroEmm** [comment]
Yeah thats my exact problem and i run into because of the up-script that you supplied. 
I already did that: 
https://github.com/docker/docker/issues/11837#issuecomment-86750027 
but i was just curious whether you were running into the same issues? Or are you adding the IP on another interface all the time?

**Comment by discordianfish** [comment]
@AlessandroEmm Cool, thanks. I haven't seen this issue but we bind the VIP to our external interface where it looks like you bind it to the docker bridge? Or what exactly is mgm0 in your example?

**Comment by AlessandroEmm** [comment]
Yeah we bind it to the physical interface (mgm0) that docker0 is bridged to, or at least that was the idea. For the time being I will try to get around it by using another physical interface on the same network.

**Comment by discordianfish** [comment]
I think this should be tracked in the linked docker issue.
